SELECT [ProductID]
      ,[ProductName]
      ,[SupplierID]
      ,[CategoryID]
      ,[QuantityPerUnit]
      ,[UnitPrice]
  FROM [dbo].[Products]
    GROUP BY [ProductID]
      ,[ProductName]
      ,[SupplierID]
      ,[CategoryID]
      ,[QuantityPerUnit]
      ,[UnitPrice]
	HAVING [UnitPrice] > (SELECT AVG(UnitPrice) FROM [dbo].[Products])